# GitHub Sponsors button + donation links.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: poli0981
ko_fi: skullmute
buy_me_a_coffee: skullmute
patreon: skullmute
custom:
  - https://paypal.me/DungDang212
